### ISSUE TITLE
Xacro description files compatibility with ROS indigo

### ISSUE THREAD

**Issue by dogoepp** [resibots/hexapod_ros#8]
On ROS indigo, that is to say on Positronic, the xacro files result in unrealistic model of the robot. For instance, back-left leg is in the middle of the robot.

Or better, a picture:
![rviz_screenshot_2016_08_12-18_17_52](https://cloud.githubusercontent.com/assets/13215604/17629184/73c2b7a6-60b9-11e6-8196-37a269e69aa2.png)

**Comment by costashatz** [comment]
This is because in ROS Indigo, Xacro does not support python expressions whereas Jade (and newer versions) does. It is very easy to make the xacro files with python expressions. We are already 2 versions after Indigo. I think we should aim at updating positronic to the latest ROS version in a few months (when it is more stable).

**Comment by dogoepp** [comment]
Will be "fixed" by moving on to Kinetic Kate
